name: lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  luacheck:
    name: luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck
      - name: Run luacheck
        run: luacheck lua/ plugin/
  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install stylua
        uses: JohnnyMorganz/stylua-action@479972f01e665acfcba96ada452c36608bdbbb5e # v4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua/ plugin/
